### ISSUE TITLE
Failing to read rules from annotations when not using "prometheus.rules.json"

### ISSUE THREAD

**Issue by l-lafin** [philips-software/variant#35]
We are trying to configure one rule per annotation to avoid exceeding the 5000 char limit, but currently, the implementation is always expecting the annotation `prometheus.rules.json` to exist, even when you are informing rules through the pattern `prometheus.rules.*.json`.

https://github.com/philips-software/variant/blob/e9019172ed88edbba059c2cde94538b217dbd6d2/tva/utils.go#L136

**Comment by loafoe** [comment]
Fixed in `0.1.0`
