### ISSUE TITLE
Feature: Filter metrics by list of metrics

### ISSUE THREAD

**Issue by soubhagya-pradhan** [philips-software/variant#43]
This is a request to filter the list of metrics to be dropped or to be pushed from variant to thanos. Its a feature similar to metrics_relabel_configs which also comes under Thanos Rewrite section `write_relable_config` with `relable_action` .

![image](https://user-images.githubusercontent.com/81353127/173349969-4bcdfcfe-ec50-4eac-85ad-ff59b4c35162.png)

[Link](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) to remote_write relable_config
It should be configurable from cloudfoundry application or from variant side to provide a list of metrics to be denied/dropped or pushed

**Comment by loafoe** [comment]
No feedback received so assuming it works as expected, closing.
